sudo: false
language: node_js
node_js:
  - 12 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - main # build master branch only
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: main
  local-dir: public
install:
 - npm install hexo-cli -g
 - npm install
 - npm install hexo-generator-feed --save
 - npm install hexo-deployer-git --save
script:
 - hexo clean
 - hexo g
 - hexo d
