sudo: false
language: node_js
node_js:
- 12
cache: npm
branches:
  only:
  - main
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GH_TOKEN"
  keep-history: true
  on:
    branch: main
  local-dir: public
install:
- npm install hexo-cli -g
- npm install
- npm install hexo-generator-feed --save
- npm install hexo-deployer-git --save
script:
- git config --global user.name "lich-wang"
- git config --global user.email "lich.wang@gmail.com"
- hexo clean
- hexo g
- hexo d
dd:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out deploy_rsa -d
